FROM cheesesan/base:latest

RUN sudo apt-get install -y python3-pip
RUN pip3 install -U pip
RUN pip3 install jupyterlab
RUN pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu

