FROM ubuntu:18.04

RUN apt-get update && apt-get install -y neovim neofetch git zsh sudo

#RUN useradd -m bucchiman --uid=1000 && echo "bucchiman:docker" | chpasswd
#RUN chsh -s zsh
#RUN mkdir ~/git && cd ~/git && \
#    git clone https://github.com/Bucchiman/dotfiles.git \
#    && cp dotfiles/.zshrc ~ && cp dotfiles/.config ~


ARG username=bucchiman
ARG wkdir=/home/bucchiman


RUN echo "root:root" | chpasswd && \
    adduser --disabled-password --gecos "" "${username}" && \
    echo "${username}:${username}" | chpasswd && \
    echo "%${username}    ALL=(ALL)   NOPASSWD:    ALL" >> /etc/sudoers.d/${username} && \
    chmod 0440 /etc/sudoers.d/${username}

USER ${username}
WORKDIR /home/${username}
