#
# FileName:     docker-compose
# Author:       8ucchiman
# CreatedDate:  2023-12-07 14:09:22
# LastModified: 2023-12-07 14:09:24
# Reference:    https://qiita.com/yuta-ushijima/items/d3d98177e1b28f736f04
# Description:  ---
#


version: '3'    # docker-composeのバージョン指定

services:       # アプリケーションを動かすための各要素
  db:
    images: mysql
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db




